Traceback (most recent call last):
  File "/home/petri/miniforge3/envs/octave/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/petri/miniforge3/envs/octave/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petri/miniforge3/envs/octave/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petri/miniforge3/envs/octave/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/petri/miniforge3/envs/octave/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/petri/miniforge3/envs/octave/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/petri/miniforge3/envs/octave/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
D.loc['2014-10-01':'2014-10-02', 'Irradiance':'Heatflux']
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[19], line 1[0m
[0;32m----> 1[0m [43mD[49m[38;5;241;43m.[39;49m[43mloc[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43m2014-10-01[39;49m[38;5;124;43m'[39;49m[43m:[49m[38;5;124;43m'[39;49m[38;5;124;43m2014-10-02[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mIrradiance[39;49m[38;5;124;43m'[39;49m[43m:[49m[38;5;124;43m'[39;49m[38;5;124;43mHeatflux[39;49m[38;5;124;43m'[39;49m[43m][49m

File [0;32m~/miniforge3/envs/octave/lib/python3.11/site-packages/pandas/core/indexing.py:1185[0m, in [0;36m_LocationIndexer.__getitem__[0;34m(self, key)[0m
[1;32m   1183[0m     [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_is_scalar_access(key):
[1;32m   1184[0m         [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39mobj[38;5;241m.[39m_get_value([38;5;241m*[39mkey, takeable[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39m_takeable)
[0;32m-> 1185[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_getitem_tuple[49m[43m([49m[43mkey[49m[43m)[49m
[1;32m   1186[0m [38;5;28;01melse[39;00m:
[1;32m   1187[0m     [38;5;66;03m# we by definition only have the 0th axis[39;00m
[1;32m   1188[0m     axis [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39maxis [38;5;129;01mor[39;00m [38;5;241m0[39m

File [0;32m~/miniforge3/envs/octave/lib/python3.11/site-packages/pandas/core/indexing.py:1378[0m, in [0;36m_LocIndexer._getitem_tuple[0;34m(self, tup)[0m
[1;32m   1375[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_multi_take_opportunity(tup):
[1;32m   1376[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_multi_take(tup)
[0;32m-> 1378[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_getitem_tuple_same_dim[49m[43m([49m[43mtup[49m[43m)[49m

File [0;32m~/miniforge3/envs/octave/lib/python3.11/site-packages/pandas/core/indexing.py:1021[0m, in [0;36m_LocationIndexer._getitem_tuple_same_dim[0;34m(self, tup)[0m
[1;32m   1018[0m [38;5;28;01mif[39;00m com[38;5;241m.[39mis_null_slice(key):
[1;32m   1019[0m     [38;5;28;01mcontinue[39;00m
[0;32m-> 1021[0m retval [38;5;241m=[39m [38;5;28;43mgetattr[39;49m[43m([49m[43mretval[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mname[49m[43m)[49m[38;5;241;43m.[39;49m[43m_getitem_axis[49m[43m([49m[43mkey[49m[43m,[49m[43m [49m[43maxis[49m[38;5;241;43m=[39;49m[43mi[49m[43m)[49m
[1;32m   1022[0m [38;5;66;03m# We should never have retval.ndim < self.ndim, as that should[39;00m
[1;32m   1023[0m [38;5;66;03m#  be handled by the _getitem_lowerdim call above.[39;00m
[1;32m   1024[0m [38;5;28;01massert[39;00m retval[38;5;241m.[39mndim [38;5;241m==[39m [38;5;28mself[39m[38;5;241m.[39mndim

File [0;32m~/miniforge3/envs/octave/lib/python3.11/site-packages/pandas/core/indexing.py:1412[0m, in [0;36m_LocIndexer._getitem_axis[0;34m(self, key, axis)[0m
[1;32m   1410[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(key, [38;5;28mslice[39m):
[1;32m   1411[0m     [38;5;28mself[39m[38;5;241m.[39m_validate_key(key, axis)
[0;32m-> 1412[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_get_slice_axis[49m[43m([49m[43mkey[49m[43m,[49m[43m [49m[43maxis[49m[38;5;241;43m=[39;49m[43maxis[49m[43m)[49m
[1;32m   1413[0m [38;5;28;01melif[39;00m com[38;5;241m.[39mis_bool_indexer(key):
[1;32m   1414[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_getbool_axis(key, axis[38;5;241m=[39maxis)

File [0;32m~/miniforge3/envs/octave/lib/python3.11/site-packages/pandas/core/indexing.py:1444[0m, in [0;36m_LocIndexer._get_slice_axis[0;34m(self, slice_obj, axis)[0m
[1;32m   1441[0m     [38;5;28;01mreturn[39;00m obj[38;5;241m.[39mcopy(deep[38;5;241m=[39m[38;5;28;01mFalse[39;00m)
[1;32m   1443[0m labels [38;5;241m=[39m obj[38;5;241m.[39m_get_axis(axis)
[0;32m-> 1444[0m indexer [38;5;241m=[39m [43mlabels[49m[38;5;241;43m.[39;49m[43mslice_indexer[49m[43m([49m[43mslice_obj[49m[38;5;241;43m.[39;49m[43mstart[49m[43m,[49m[43m [49m[43mslice_obj[49m[38;5;241;43m.[39;49m[43mstop[49m[43m,[49m[43m [49m[43mslice_obj[49m[38;5;241;43m.[39;49m[43mstep[49m[43m)[49m
[1;32m   1446[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(indexer, [38;5;28mslice[39m):
[1;32m   1447[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39mobj[38;5;241m.[39m_slice(indexer, axis[38;5;241m=[39maxis)

File [0;32m~/miniforge3/envs/octave/lib/python3.11/site-packages/pandas/core/indexes/datetimes.py:697[0m, in [0;36mDatetimeIndex.slice_indexer[0;34m(self, start, end, step)[0m
[1;32m    694[0m     in_index [38;5;241m&[39m[38;5;241m=[39m (end_casted [38;5;241m==[39m [38;5;28mself[39m)[38;5;241m.[39many()
[1;32m    696[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m in_index:
[0;32m--> 697[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m(
[1;32m    698[0m         [38;5;124m"[39m[38;5;124mValue based partial slicing on non-monotonic DatetimeIndexes [39m[38;5;124m"[39m
[1;32m    699[0m         [38;5;124m"[39m[38;5;124mwith non-existing keys is not allowed.[39m[38;5;124m"[39m,
[1;32m    700[0m     )
[1;32m    701[0m indexer [38;5;241m=[39m mask[38;5;241m.[39mnonzero()[[38;5;241m0[39m][::step]
[1;32m    702[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(indexer) [38;5;241m==[39m [38;5;28mlen[39m([38;5;28mself[39m):

[0;31mKeyError[0m: 'Value based partial slicing on non-monotonic DatetimeIndexes with non-existing keys is not allowed.'

