Traceback (most recent call last):
  File "/home/petri/miniforge3/envs/octave/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/petri/miniforge3/envs/octave/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petri/miniforge3/envs/octave/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/petri/miniforge3/envs/octave/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/petri/miniforge3/envs/octave/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/petri/miniforge3/envs/octave/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/petri/miniforge3/envs/octave/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from sklearn.neighbors.nearest_centroid import NearestCentroid
pipelineCentroid=Pipeline([
        ('Scaling', StandardScaler()),
        ('KNN', NearestCentroid())
    ])
pipelineCentroid.fit(X2s,y2)
predictedY=pipelineCentroid.predict(X2s)
print(metrics.accuracy_score(y_true=y2, y_pred=predictedY))
plotDB(pipelineCentroid, X2s, y2)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[12], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mneighbors[39;00m[38;5;21;01m.[39;00m[38;5;21;01mnearest_centroid[39;00m [38;5;28;01mimport[39;00m NearestCentroid
[1;32m      2[0m pipelineCentroid[38;5;241m=[39mPipeline([
[1;32m      3[0m         ([38;5;124m'[39m[38;5;124mScaling[39m[38;5;124m'[39m, StandardScaler()),
[1;32m      4[0m         ([38;5;124m'[39m[38;5;124mKNN[39m[38;5;124m'[39m, NearestCentroid())
[1;32m      5[0m     ])
[1;32m      6[0m pipelineCentroid[38;5;241m.[39mfit(X2s,y2)

[0;31mModuleNotFoundError[0m: No module named 'sklearn.neighbors.nearest_centroid'

